version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Abc123456.
      MYSQL_DATABASE: chatdata  # 自动创建数据库
    ports:
      - "3306:3306"
    networks:
      - chat-net

  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - server1
      - server2
    networks:
      - chat-net
    
  server1:
    build: .
    command: ["./bin/ChatServer", "127.0.0.1", "6000"]
    depends_on:
      - mysql
      - redis
    networks:
      - chat-net

  server2:
    build: .
    command: ["./bin/ChatServer", "127.0.0.1", "6001"]
    depends_on:
      - mysql
      - redis
    networks:
      - chat-net

networks:
  chat-net:  # 自定义网络，容器间通信用服务名

prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /tmp:/tmp  # 共享tmp目录，让prometheus能读文件
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus